/**
 * NexusAI — Subscription Plan Definitions
 * Source of truth for plan features, limits, pricing, and model access.
 * Backend validates these server-side; this copy drives the UI gating.
 */

import type { SubscriptionPlan } from "../types/subscription";

export const SUBSCRIPTION_PLANS: Record<string, SubscriptionPlan> = {

  starter: {
    id:          "plan_starter_v3",
    code:        "starter",
    name:        "Starter",
    description: "For emerging fintechs and credit unions starting their AML journey.",
    basePrice:   { amount: 299900, currency: "CAD" },   // CA$2,999/mo
    billingCycle: "monthly",
    trialDays:   14,
    isPublic:    true,
    seats: { included: 3,  max: 5,           perSeatPrice: { amount: 49900,  currency: "CAD" } },
    limits: {
      apiRequestsPerMonth:   50_000,
      aiTokensPerMonth:      2_000_000,
      sarPerMonth:           20,
      kycChecksPerMonth:     500,
      vectorStorageMB:       1_024,
      documentPagesPerMonth: 500,
      alertsPerMonth:        1_000,
      webhooksPerDay:        100,
      dataRetentionDays:     90,
      apiKeys:               2,
      rateLimits: {
        requestsPerSecond:   5,
        requestsPerMinute:   200,
        requestsPerHour:     5_000,
        tokensPerMinute:     40_000,
        concurrentRequests:  5,
        burstAllowed:        false,
      },
    },
    features: {
      amlAlertQueue:         true,
      riskScoring:           true,
      entityNetworkGraph:    true,
      transactionMonitoring: true,
      sarGenerator:          true,
      fintracReporting:      true,
      customReports:         false,
      exportCSV:             true,
      exportPDF:             false,
      agenticInvestigator:   false,
      aiExplainability:      false,
      federatedLearning:     false,
      ragPipeline:           false,
      customEmbeddings:      false,
      fineTunedModels:       false,
      perpetualKyc:          false,
      sanctionsScreening:    true,
      pepScreening:          false,
      adverseMediaScreening: false,
      uboDiscovery:          false,
      cryptoForensics:       false,
      rulesEngine:           true,
      customRules:           false,
      auditTrail:            true,
      immutableAuditExport:  false,
      ssoSaml:               false,
      ssoOidc:               false,
      customDomain:          false,
      whiteLabel:            false,
      "siem Integration":    false,
      ipAllowlisting:        false,
      dedicatedInfra:        false,
      bringYourOwnKey:       false,
    },
    models: {
      primary:   "standard",
      fallback:  "standard",
      embedding: "text-embedding-3-small",
    },
    support: {
      responseTimeSLA: "4h",
      channels:        ["email"],
      onboarding:      "self_serve",
      trainingIncluded: false,
    },
    sla: { uptimePercent: 99.5, rpoHours: 24, rtoHours: 8 },
  },

  professional: {
    id:          "plan_professional_v3",
    code:        "professional",
    name:        "Professional",
    description: "For growing compliance teams at mid-size banks and fintechs.",
    basePrice:   { amount: 999900, currency: "CAD" },   // CA$9,999/mo
    billingCycle: "monthly",
    trialDays:   14,
    isPublic:    true,
    seats: { included: 10, max: 25,          perSeatPrice: { amount: 39900,  currency: "CAD" } },
    limits: {
      apiRequestsPerMonth:   500_000,
      aiTokensPerMonth:      20_000_000,
      sarPerMonth:           200,
      kycChecksPerMonth:     5_000,
      vectorStorageMB:       10_240,
      documentPagesPerMonth: 5_000,
      alertsPerMonth:        10_000,
      webhooksPerDay:        1_000,
      dataRetentionDays:     365,
      apiKeys:               10,
      rateLimits: {
        requestsPerSecond:   20,
        requestsPerMinute:   800,
        requestsPerHour:     20_000,
        tokensPerMinute:     200_000,
        concurrentRequests:  20,
        burstAllowed:        true,
      },
    },
    features: {
      amlAlertQueue:         true,
      riskScoring:           true,
      entityNetworkGraph:    true,
      transactionMonitoring: true,
      sarGenerator:          true,
      fintracReporting:      true,
      customReports:         true,
      exportCSV:             true,
      exportPDF:             true,
      agenticInvestigator:   true,
      aiExplainability:      true,
      federatedLearning:     false,
      ragPipeline:           true,
      customEmbeddings:      false,
      fineTunedModels:       false,
      perpetualKyc:          true,
      sanctionsScreening:    true,
      pepScreening:          true,
      adverseMediaScreening: true,
      uboDiscovery:          true,
      cryptoForensics:       false,
      rulesEngine:           true,
      customRules:           true,
      auditTrail:            true,
      immutableAuditExport:  true,
      ssoSaml:               true,
      ssoOidc:               true,
      customDomain:          false,
      whiteLabel:            false,
      "siem Integration":    true,
      ipAllowlisting:        true,
      dedicatedInfra:        false,
      bringYourOwnKey:       false,
    },
    models: {
      primary:   "advanced",
      fallback:  "standard",
      embedding: "text-embedding-3-large",
    },
    support: {
      responseTimeSLA: "1h",
      channels:        ["email", "chat"],
      onboarding:      "guided",
      trainingIncluded: true,
    },
    sla: { uptimePercent: 99.9, rpoHours: 4, rtoHours: 2 },
  },

  enterprise: {
    id:          "plan_enterprise_v3",
    code:        "enterprise",
    name:        "Enterprise",
    description: "For Tier 1 banks and large financial institutions at scale.",
    basePrice:   { amount: 4999900, currency: "CAD" }, // CA$49,999/mo — custom pricing
    billingCycle: "annual",
    trialDays:   0,
    isPublic:    false,                                // sales-led only
    seats: { included: 50, max: "unlimited" },
    limits: {
      apiRequestsPerMonth:   "unlimited",
      aiTokensPerMonth:      "unlimited",
      sarPerMonth:           "unlimited",
      kycChecksPerMonth:     "unlimited",
      vectorStorageMB:       "unlimited",
      documentPagesPerMonth: "unlimited",
      alertsPerMonth:        "unlimited",
      webhooksPerDay:        "unlimited",
      dataRetentionDays:     2_555,                   // 7 years (OSFI requirement)
      apiKeys:               100,
      rateLimits: {
        requestsPerSecond:   100,
        requestsPerMinute:   4_000,
        requestsPerHour:     100_000,
        tokensPerMinute:     1_000_000,
        concurrentRequests:  100,
        burstAllowed:        true,
      },
    },
    features: {
      amlAlertQueue:         true,
      riskScoring:           true,
      entityNetworkGraph:    true,
      transactionMonitoring: true,
      sarGenerator:          true,
      fintracReporting:      true,
      customReports:         true,
      exportCSV:             true,
      exportPDF:             true,
      agenticInvestigator:   true,
      aiExplainability:      true,
      federatedLearning:     true,
      ragPipeline:           true,
      customEmbeddings:      true,
      fineTunedModels:       true,
      perpetualKyc:          true,
      sanctionsScreening:    true,
      pepScreening:          true,
      adverseMediaScreening: true,
      uboDiscovery:          true,
      cryptoForensics:       true,
      rulesEngine:           true,
      customRules:           true,
      auditTrail:            true,
      immutableAuditExport:  true,
      ssoSaml:               true,
      ssoOidc:               true,
      customDomain:          true,
      whiteLabel:            true,
      "siem Integration":    true,
      ipAllowlisting:        true,
      dedicatedInfra:        true,
      bringYourOwnKey:       true,
    },
    models: {
      primary:   "premium",
      fallback:  "advanced",
      embedding: "text-embedding-3-large",
    },
    support: {
      responseTimeSLA: "15min",
      channels:        ["email", "chat", "phone", "dedicated_csm"],
      onboarding:      "white_glove",
      trainingIncluded: true,
    },
    sla: { uptimePercent: 99.99, rpoHours: 1, rtoHours: 0.5, penaltyPolicy: "service_credit_10pct" },
  },

  government: {
    id:          "plan_government_v3",
    code:        "government",
    name:        "Government",
    description: "For FINTRAC, OSFI, Bank of Canada, and federal financial regulators.",
    basePrice:   { amount: 0, currency: "CAD" },       // custom — procurement process
    billingCycle: "multi_year",
    trialDays:   0,
    isPublic:    false,
    seats: { included: 200, max: "unlimited" },
    limits: {
      apiRequestsPerMonth:   "unlimited",
      aiTokensPerMonth:      "unlimited",
      sarPerMonth:           "unlimited",
      kycChecksPerMonth:     "unlimited",
      vectorStorageMB:       "unlimited",
      documentPagesPerMonth: "unlimited",
      alertsPerMonth:        "unlimited",
      webhooksPerDay:        "unlimited",
      dataRetentionDays:     3_650,                   // 10 years
      apiKeys:               "unlimited" as unknown as number,
      rateLimits: {
        requestsPerSecond:   500,
        requestsPerMinute:   10_000,
        requestsPerHour:     500_000,
        tokensPerMinute:     5_000_000,
        concurrentRequests:  500,
        burstAllowed:        true,
      },
    },
    features: {
      amlAlertQueue:         true, riskScoring: true, entityNetworkGraph: true,
      transactionMonitoring: true, sarGenerator: true, fintracReporting: true,
      customReports:         true, exportCSV: true, exportPDF: true,
      agenticInvestigator:   true, aiExplainability: true, federatedLearning: true,
      ragPipeline:           true, customEmbeddings: true, fineTunedModels: true,
      perpetualKyc:          true, sanctionsScreening: true, pepScreening: true,
      adverseMediaScreening: true, uboDiscovery: true, cryptoForensics: true,
      rulesEngine:           true, customRules: true, auditTrail: true,
      immutableAuditExport:  true, ssoSaml: true, ssoOidc: true, customDomain: true,
      whiteLabel:            true, "siem Integration": true, ipAllowlisting: true,
      dedicatedInfra:        true, bringYourOwnKey: true,
    },
    models: {
      primary:   "premium",
      fallback:  "premium",
      embedding: "text-embedding-3-large",
      custom:    ["nexusai-fintrac-v1"],               // sovereign fine-tuned model
    },
    support: {
      responseTimeSLA: "15min",
      channels:        ["email", "chat", "phone", "dedicated_csm"],
      onboarding:      "white_glove",
      trainingIncluded: true,
    },
    sla: { uptimePercent: 99.999, rpoHours: 0.25, rtoHours: 0.25, penaltyPolicy: "contractual" },
  },
};

export function getPlan(code: string): SubscriptionPlan {
  return SUBSCRIPTION_PLANS[code] ?? SUBSCRIPTION_PLANS.starter;
}

export function isFeatureAllowed(planCode: string, feature: keyof SubscriptionPlan["features"]): boolean {
  return getPlan(planCode).features[feature] === true;
}

export function getLimitValue(planCode: string, limit: keyof SubscriptionPlan["limits"]): number | "unlimited" {
  return getPlan(planCode).limits[limit as keyof typeof SUBSCRIPTION_PLANS["starter"]["limits"]] as number | "unlimited";
}
